### ISSUE TITLE
OAuth : Passport API creation

### ISSUE THREAD

**Issue by thanjeys** [LaravelDaily/Laravel-Roadmap-Learning-Path#15]
Hi, 

Can you think about topic to add "Passport API creation : OAuth " ? 

Thanks

**Comment by PovilasKorop** [comment]
@thanjeys great idea, how could I miss it. Will add it somewhere.

**Comment by thanjeys** [comment]
@PovilasKorop  Thank you. you are doing very good job. Fantastic keep it up.

**Comment by PovilasKorop** [comment]
@thanjeys fixed in https://github.com/LaravelDaily/Laravel-Roadmap-Learning-Path/commit/f65cd163701dea7e0a7eb6638d9d6c33bfa59883
