### ISSUE TITLE
Remove roadmap.sql to facilitate contributions?

### ISSUE THREAD

**Issue by devnll** [LaravelDaily/Laravel-Roadmap-Learning-Path#2]
Love the idea behind this project.

I have a small suggestion. I think contributing to (and maintaining) this project would be easier / less error-prone if there was a "single source of truth" for the data. For example, `roadmap.sql` could be replaced with a script that generates the appropriate SQL based on the contents of `readme.md`. Then, a potential contributor would only need to submit a PR with their modifications to `readme.md`, and wouldn't have to worry about making the corresponding modifications to `roadmap.sql`.

Also, instead of SQL might it be preferable for the script to generate JSON or some other generic format? I suppose it depends on the intended audience for this repo, but might be worth considering.

**Comment by PovilasKorop** [comment]
@devnll interesting point, I didn't think about it, that maybe the SQL file in the repo prevents others to contribute with their suggestions.

But, at the same time, that SQL format may be useful for people who want to visualize it differently than just the Github table.

So I think it brings more value than causes harm, if someone wants to contribute then they may still open the issue first and discuss it. Actually, my plan was that I personally update the SQL file whenever some contribution is made in the Markdown file. But we'll see if it's actually even a problem after a few people show their interest to contribute.

**Comment by devnll** [comment]
Ah, makes sense. Best of luck with the project!
