### ISSUE TITLE
Why did you remove Skill test of topics (Routes , Blade.. etc )  

### ISSUE THREAD

**Issue by thanjeys** [LaravelDaily/Laravel-Roadmap-Learning-Path#22]
Hi, 

Why did you remove Skill test of topics (Routes , Blade.. etc ) . 

Becoz it is very helpful for developer to prepare well. Thanks

**Comment by PovilasKorop** [comment]
@thanjeys what do you mean remove? From where?

**Comment by PovilasKorop** [comment]
@thanjeys @neomn oh now I see what you mean, I've missed this change in this PR: https://github.com/LaravelDaily/Laravel-Roadmap-Learning-Path/pull/21 - will return it back

**Comment by neomn** [comment]
@PovilasKorop  thanks 🙏👍🌹
