### ISSUE TITLE
Wrong linking of 'Defining Model Factories' to Laravel official documentation

### ISSUE THREAD

**Issue by alnahian2003** [LaravelDaily/Laravel-Roadmap-Learning-Path#28]
Hi there,
![image](https://user-images.githubusercontent.com/61485238/197217968-4487bfb8-41ba-406b-a208-b88c0062821a.png)
I think in the Advanced Beginner Level, 'Defining Model Factories' link should be this one: **https://laravel.com/docs/9.x/eloquent-factories#defining-model-factories** , and not the existing one!

Because the current link leads to the **Database Testing** related documentation, which is literally irrelevant here.

Have a tremendous day!

**Comment by spekulatius** [comment]
Hey @alnahian2003 

good spotting. I've done a quick PR to fix it :muscle: 

Cheers,
Peter

**Comment by alnahian2003** [comment]
Glad to know! Thanks for fixing the issue.
