### ISSUE TITLE
🔠 Request to Add Multi-Language and Translation topic in the Roadmap

### ISSUE THREAD

**Issue by alnahian2003** [LaravelDaily/Laravel-Roadmap-Learning-Path#31]
Hey there!

I wanted to drop a quick note about the Laravel Roadmap Learning Path. I've been following the Intermediate path lately and noticed a missing topic that would be awesome to include: Multi-Language/Localization in Laravel.

---

Here are some fantastic resources that I believe should be added to the Intermediate section:

```

Official Documentation:
📖 [Official Documentation on Localization](https://laravel.com/docs/localization)

Courses:
🔠 [Multi-Language Laravel](https://laraveldaily.com/course/multi-language-laravel)

Articles:
📄 [Multi-Language Routes and Locales with Authentication](https://laraveldaily.com/post/multi-language-routes-and-locales-with-auth)
📄 [Laravel Localization Made Easy](https://www.linkedin.com/pulse/laravel-localization-made-easy-fun-guide-going-binu-mathew)
📄 [Easy Laravel Localization Tutorial with Blog Use Case and Repository Example](https://fajarwz.com/blog/easy-laravel-localization-tutorial-with-blog-use-case-and-repo-example)

Videos:
🎬 [Multi-Language Laravel: Part 1 - Static Texts](https://youtu.be/Fbw1-5WaJDU)
🎬 [Multi-Language Laravel: Part 2 - DB Models with "title_en"](https://youtu.be/Owb3sWVqmvo)
🎬 [Multi-Language Laravel: Part 3 - Packages for DB Models](https://youtu.be/9K75rpsipho)
🎬 [Laravel: Single to Multi-Language - Practical Demo](https://youtu.be/lEccoYhzyos)
```

---

I believe adding these resources will greatly benefit learners on the Intermediate path by providing valuable insights into Multi-Language/Localization in Laravel.

Cheers!

**Comment by PovilasKorop** [comment]
@alnahian2003 ok thanks for the suggestion, I will add these ones to the roadmap later this week.

**Comment by alnahian2003** [comment]
Aw that's great! Looking forward to it 👌

**Comment by PovilasKorop** [comment]
@alnahian2003 added it to the web version of the roadmap, as it's the "official" one now: https://laraveldaily.com/roadmap-learning-path 

This GitHub version is kind of "deprecated" in a way, maybe will update it with changes later, if there are more changes at some point and I have more free time.

Thanks for your help!

**Comment by alnahian2003** [comment]
Great, that's coool! Thanks for the update
