### ISSUE TITLE
Please move the emoji legend/key out of the Column Header

### ISSUE THREAD

**Issue by zersiax** [LaravelDaily/Laravel-Roadmap-Learning-Path#9]
When the header of a column in a Markdown table gets converted to HTML , that header becomes the semantic column header for that column in the HTML table. This is usually a good thing.
One side effect of this is that screenreaders will, when encountering a cell in that column, helpfully read the column header again before the cell contents. This is done because a blind/VI computer user can only see one thing at a time, and it makes it easier to associate the cell with it's column and/or row headers. Again, this is usually a good thing.
In this table however, the column header is several lines long, with a lot of info. This means that the text Learning Links(Open Book Official Docs ClapperBoard Video PageFacingUp Article InputLatinUppercase Course) is prepended to every cell contents when the cell is encountered. This is, euphemistically said, extremely annoying :)
Love the resource, don't love the time I'm losing by this little glitch. Could you move the emoji guide out of the table, or would you accept a pull request doing this? :) Thanks for reading in any case.

**Comment by PovilasKorop** [comment]
@zersiax thanks for such a detailed explanation. Done and fixed in the Pull Request #10

**Comment by zersiax** [comment]
Much better, thanks a lot :)
